version: '3.4'

services:
  skoruba.identityserver4.admin:
    image: ${DOCKER_REGISTRY-}identityserver4-admin:${TAG}
    expose:
      - 80 
    ports:
      - ${ADMIN_URL_PORT}:80
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.Admin/Dockerfile-windows
    container_name: skoruba-identityserver4-admin
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=${ADMIN_URL}"
      - "AdminConfiguration__IdentityAdminRedirectUri=${ADMIN_URL}/signin-oidc"
      - "AdminConfiguration__IdentityServerBaseUrl=${BASE_URL}"
      - "AdminConfiguration__RequireHttpsMetadata=false"
      - "IdentityServerData__Clients__0__ClientUri=${ADMIN_URL}"
      - "IdentityServerData__Clients__0__RedirectUris__0=${ADMIN_URL}/signin-oidc"
      - "IdentityServerData__Clients__0__FrontChannelLogoutUri=${ADMIN_URL}/signin-oidc"
      - "IdentityServerData__Clients__0__PostLogoutRedirectUris__0=${ADMIN_URL}/signout-callback-oidc"
      - "IdentityServerData__Clients__0__AllowedCorsOrigins__0=${ADMIN_URL}"
      - "IdentityServerData__Clients__1__RedirectUris__0=${ADMIN_API_URL}/swagger/oauth2-redirect.html"
      - "Serilog__WriteTo__1__Args__connectionString=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
    command: dotnet Skoruba.IdentityServer4.Admin.dll /seed
    depends_on:
      - db
      - skoruba.identityserver4.sts.identity
    # volumes:
    #   - "./shared/serilog.json:C:/app/serilog.json"
    #   - "./shared/identitydata.json:C:/app/identitydata.json"
    #   - "./shared/identityserverdata.json:C:/app/identityserverdata.json"

  skoruba.identityserver4.admin.api:
    image: ${DOCKER_REGISTRY-}identityserver4-admin-api:${TAG}
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.Admin.Api/Dockerfile-windows
    depends_on:
      - db
    expose:
      - 80 
    ports:
      - ${ADMIN_API_URL_PORT}:80
    environment:
      - "AdminApiConfiguration__RequireHttpsMetadata=false"
      - "AdminApiConfiguration__ApiBaseUrl=${ADMIN_API_URL}"
      - "AdminApiConfiguration__IdentityServerBaseUrl=${BASE_URL}"
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
    container_name: skoruba-identityserver4-admin-api
    # volumes:
    #   - "./shared/serilog.json:/app/serilog.json"

  skoruba.identityserver4.sts.identity:
    image: ${DOCKER_REGISTRY-}identityserver4-sts-identity:${TAG}
    container_name: skoruba-identityserver4-sts-identity
    expose:
      - 80 
    ports:
      - ${BASE_URL_PORT}:80
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.STS.Identity/Dockerfile-windows
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConfigurationDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=db;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=${ADMIN_URL}"
    # volumes:
    #   - "./shared/serilog.json:C:/app/serilog.json"
    networks:
      default:
        aliases:
          - 127.0.0.1.xip.io
  db:
    image: microsoft/mssql-server-windows-express
    expose:
      - 1433
    ports:
      - 1433:1433
    container_name: skoruba-identityserver4-db
    environment:
      SA_PASSWORD: "${DB_PASSWORD:-Password_123}"
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:C:/Data

volumes:
  dbdata:
    driver: local

# networks:
#   default:
#     driver: bridge