//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skoruba.IdentityServer4.Admin.BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResourceServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResourceServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skoruba.IdentityServer4.Admin.BusinessLogic.Resources.ApiResourceServiceResource", typeof(ApiResourceServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Resource with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string ApiResourceDoesNotExist {
            get {
                return ResourceManager.GetString("ApiResourceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Resource already exists.
        /// </summary>
        internal static string ApiResourceExistsKey {
            get {
                return ResourceManager.GetString("ApiResourceExistsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Resource ({0}) already exists.
        /// </summary>
        internal static string ApiResourceExistsValue {
            get {
                return ResourceManager.GetString("ApiResourceExistsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Resource Property with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string ApiResourcePropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ApiResourcePropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Resource Property already exists.
        /// </summary>
        internal static string ApiResourcePropertyExistsKey {
            get {
                return ResourceManager.GetString("ApiResourcePropertyExistsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Resource Property with key ({0}) already exists.
        /// </summary>
        internal static string ApiResourcePropertyExistsValue {
            get {
                return ResourceManager.GetString("ApiResourcePropertyExistsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Scope with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string ApiScopeDoesNotExist {
            get {
                return ResourceManager.GetString("ApiScopeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Scope already exists.
        /// </summary>
        internal static string ApiScopeExistsKey {
            get {
                return ResourceManager.GetString("ApiScopeExistsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Scope ({0}) already exists.
        /// </summary>
        internal static string ApiScopeExistsValue {
            get {
                return ResourceManager.GetString("ApiScopeExistsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Secret with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string ApiSecretDoesNotExist {
            get {
                return ResourceManager.GetString("ApiSecretDoesNotExist", resourceCulture);
            }
        }
    }
}
