//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdentityServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Resources.IdentityServiceResource", typeof(IdentityServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string IdentityErrorKey {
            get {
                return ResourceManager.GetString("IdentityErrorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role claim with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string RoleClaimDoesNotExist {
            get {
                return ResourceManager.GetString("RoleClaimDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Claims creating failed.
        /// </summary>
        internal static string RoleClaimsCreateFailed {
            get {
                return ResourceManager.GetString("RoleClaimsCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Claims deleting failed.
        /// </summary>
        internal static string RoleClaimsDeleteFailed {
            get {
                return ResourceManager.GetString("RoleClaimsDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role creating failed.
        /// </summary>
        internal static string RoleCreateFailed {
            get {
                return ResourceManager.GetString("RoleCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deleting failed.
        /// </summary>
        internal static string RoleDeleteFailed {
            get {
                return ResourceManager.GetString("RoleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string RoleDoesNotExist {
            get {
                return ResourceManager.GetString("RoleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role updating failed.
        /// </summary>
        internal static string RoleUpdateFailed {
            get {
                return ResourceManager.GetString("RoleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Change Password failed.
        /// </summary>
        internal static string UserChangePasswordFailed {
            get {
                return ResourceManager.GetString("UserChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User claim with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string UserClaimDoesNotExist {
            get {
                return ResourceManager.GetString("UserClaimDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Claims creating failed.
        /// </summary>
        internal static string UserClaimsCreateFailed {
            get {
                return ResourceManager.GetString("UserClaimsCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Claims deleting failed.
        /// </summary>
        internal static string UserClaimsDeleteFailed {
            get {
                return ResourceManager.GetString("UserClaimsDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creating failed.
        /// </summary>
        internal static string UserCreateFailed {
            get {
                return ResourceManager.GetString("UserCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleting failed.
        /// </summary>
        internal static string UserDeleteFailed {
            get {
                return ResourceManager.GetString("UserDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Provider deleting failed.
        /// </summary>
        internal static string UserProviderDeleteFailed {
            get {
                return ResourceManager.GetString("UserProviderDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User provider with id {0} doesn&apos;t exist.
        /// </summary>
        internal static string UserProviderDoesNotExist {
            get {
                return ResourceManager.GetString("UserProviderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role creating failed.
        /// </summary>
        internal static string UserRoleCreateFailed {
            get {
                return ResourceManager.GetString("UserRoleCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role deleting failed.
        /// </summary>
        internal static string UserRoleDeleteFailed {
            get {
                return ResourceManager.GetString("UserRoleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updating failed.
        /// </summary>
        internal static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }
    }
}
