name: nuget publish

on: push

jobs:
  publish:

    name: publish

    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/lobsterink/index.json
          dotnet-version: 3.1.100
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: show git token (workaround)
        run:  echo $secrets.GITHUB_TOKEN
        
      - name: run tests
        run: | 
            dotnet test ./tests/Skoruba.IdentityServer4.Admin.Api.IntegrationTests -c Release
            dotnet test ./tests/Skoruba.IdentityServer4.Admin.IntegrationTests -c Release
            dotnet test ./tests/Skoruba.IdentityServer4.Admin.UnitTests -c Release
            dotnet test ./tests/Skoruba.IdentityServer4.STS.Identity.IntegrationTests -c Release

      - name: generate nuget
        run: |
          if [[ $GITHUB_REF == "refs/heads/master" ]]; then
            dotnet pack src/Skoruba.IdentityServer4.Admin.BusinessLogic/Skoruba.IdentityServer4.Admin.BusinessLogic.csproj -c Release -o .
            dotnet pack src/Skoruba.IdentityServer4.Admin.BusinessLogic.Identity/Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.csproj -c Release -o .
            dotnet pack src/Skoruba.IdentityServer4.Admin.EntityFramework/Skoruba.IdentityServer4.Admin.EntityFramework.csproj -c Release -o .
            dotnet pack src/Skoruba.IdentityServer4.Admin.EntityFramework.Identity/Skoruba.IdentityServer4.Admin.EntityFramework.Identity.csproj -c Release -o .
          else
            utcnow=$(date +%s) 
            dotnet pack src/Skoruba.IdentityServer4.Admin.BusinessLogic/Skoruba.IdentityServer4.Admin.BusinessLogic.csproj -c Release -o . --version-suffix preview.$utcnow
            dotnet pack src/Skoruba.IdentityServer4.Admin.BusinessLogic.Identity/Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.csproj -c Release -o . --version-suffix preview.$utcnow
            dotnet pack src/Skoruba.IdentityServer4.Admin.EntityFramework/Skoruba.IdentityServer4.Admin.EntityFramework.csproj -c Release -o . --version-suffix preview.$utcnow
            dotnet pack src/Skoruba.IdentityServer4.Admin.EntityFramework.Identity/Skoruba.IdentityServer4.Admin.EntityFramework.Identity.csproj -c Release -o . --version-suffix preview.$utcnow
          fi

      - name: get version and push 1
        run: |
          nugetFileName=$(find . -name "Skoruba.IdentityServer4.Admin.BusinessLogic.[!Identity]*.nupkg")
          version=$(echo $nugetFileName | grep -oP '(?<=Skoruba.IdentityServer4.Admin.BusinessLogic.)\S+(?=.nupkg)')
          echo "::set-env name=NUGET_VERSION::$version"
          dotnet nuget push Skoruba.IdentityServer4.Admin.BusinessLogic.$version.nupkg --skip-duplicate --no-symbols true
        - name: get version and push 2
          run: |
          nugetFileName=$(find . -name "Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.*.nupkg")
          version=$(echo $nugetFileName | grep -oP '(?<=Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.)\S+(?=.nupkg)')
          echo "::set-env name=NUGET_VERSION::$version"         
          dotnet nuget push Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.$version.nupkg --skip-duplicate --no-symbols true
        - name: get version and push 3
          run: |
          nugetFileName=$(find . -name "Skoruba.IdentityServer4.Admin.EntityFramework.[!Identity]*.nupkg")
          version=$(echo $nugetFileName | grep -oP '(?<=Skoruba.IdentityServer4.Admin.EntityFramework.)\S+(?=.nupkg)')
          echo "::set-env name=NUGET_VERSION::$version"
          dotnet nuget push Skoruba.IdentityServer4.Admin.EntityFramework.$version.nupkg --skip-duplicate --no-symbols true
        - name: get version and push 4
          run: |
          nugetFileName=$(find . -name "Skoruba.IdentityServer4.Admin.EntityFramework.Identity.*.nupkg")
          version=$(echo $nugetFileName | grep -oP '(?<=Skoruba.IdentityServer4.Admin.EntityFramework.Identity.)\S+(?=.nupkg)')
          echo "::set-env name=NUGET_VERSION::$version"
          dotnet nuget push Skoruba.IdentityServer4.Admin.EntityFramework.Identity.$version.nupkg --skip-duplicate --no-symbols true

      - name: set git tag with nuget version
        run: |
          git tag $NUGET_VERSION
          git push origin --tag